name: Publish CLI

on:
  push:
    tags:
      - "cli@*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - run: pnpm install

      - name: Build shared
        run: pnpm --filter @gear-cli/shared build

      - name: Test shared
        run: pnpm --filter @gear-cli/shared test

      - name: Build CLI
        run: pnpm --filter gear-cli build

      - name: Test CLI
        run: pnpm --filter gear-cli test

      - name: Publish shared
        run: pnpm --filter @gear-cli/shared publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish CLI
        run: pnpm --filter gear-cli publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
